wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: huggingface
    huggingface_version: 4.14.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1655338596
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 13
      4: 3.10.4
      5: 0.12.17
      6: 4.14.1
      8:
      - 5
