wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1655343839
    t:
      1:
      - 55
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      4: 3.10.4
      5: 0.12.17
      8:
      - 5
